### ISSUE TITLE
New server purchase by someone with a subuser on panel results in error

### ISSUE THREAD

**Issue by joker-119** [TrixterTheTux/Pterodactyl-WHMCS#129] opened 2022-09-28 06:17 UTC
Basically the title.
If someone makes a server purchase on WHMCS, but that persons email is already tied to a subuser account on the pterodactyl panel, there's an error during server creation.
Deleting their subuser account resolves the issue.

**Comment by TrixterTheTux** [comment] 2022-09-28 08:21
You’d need to include the actual error as the account already existing shouldn’t affect the module as it checks for that.

**Comment by joker-119** [comment] 2022-10-01 08:04
post - https://panel.exiled.host/api/application/users

```
{"username":"REDACTED","email":"REDACTED","first_name":"REDACTED","last_name":"REDACTED","external_id":"1114"}
````

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ValidationException
                    [status] => 422
                    [detail] => The email has already been taken.
                    [meta] => Array
                        (
                            [source_field] => email
                            [rule] => unique
                        )

                )

        )

    [status_code] => 422
)
```



get - https://panel.exiled.host/api/application/users?filter[email]=REDACTED
(returns a long list of some users, but is not a complete list and does not have the user in question on said list)



get - https://panel.exiled.host/api/application/users/external/1114
```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => NotFoundHttpException
                    [status] => 404
                    [detail] => The requested resource could not be found on the server.
                )

        )

    [status_code] => 404
)
```

**Comment by TrixterTheTux** [comment] 2022-10-01 09:37
This sounds to me like you're running the wrong version of the module for your panel, or it's just fully ignoring ?filter[email]= query string be it due to a different panel version or custom modifications.

**Comment by joker-119** [comment] 2022-10-03 03:59
Panel version 1.10.1, unsure how to check the module version, but this has always been an issue, honestly it just didn't happen enough to be a concern until recently. And it's happened on unmodded panel versions.

**Comment by joker-119** [comment] 2024-01-03 17:43
Still happening, Wings 1.11.8, Panel 1.11.2 (also tried upgrading panel to 1.11.5 and no change)

**Comment by TrixterTheTux** [comment] 2024-01-03 17:48
> This sounds to me like you're running the wrong version of the module for your panel, or it's just fully ignoring ?filter[email]= query string be it due to a different panel version or custom modifications.

This reply still applies.

**Comment by joker-119** [comment] 2024-01-25 21:40
Imagine, I update everything to the most recent version, and somehow you still think it's because something is outdated. I'm honestly amazed at your logic.

**Comment by TrixterTheTux** [comment] 2024-01-26 08:24
Here is my reasoning:
- Based on the provided module debug logs, ?filter[email]=... returns multiple matches for _an exact match_ => something is wrong either in the module or the panel
- If the module or the panel was broken out of the box, significantly more people would notice this being broken, especially when it's something as obvious as assigning the servers to the wrong user. Every company using this module would as a result have people complaining that they didn't get their paid service assigned to them, which would rather quickly be narrowed down to possibly being related to this module as it is responsible for doing the whole server creation.
- You are running a modified version of the panel based on the login page not being the default one. Thus the conclusion based on the previous points is that you have modified your panel and as a result broken some functionality in it that prevents returning the exact user based on the email match. I've also confirmed that the latest panel version does not behave like what you're claiming, thus I realistically can't provide support for the changes that you've made to your panel - but this of course would be a completely different scenario if you did run stock Pterodactyl where this issue happens.

**Comment by joker-119** [comment] 2024-01-26 11:37
Ok well my company is merging with another so in a few weeks when it happens again on a default panel just like it was before I installed a theme, I'll come back to see what the next excuse is.

**Comment by TrixterTheTux** [comment] 2024-01-26 15:07
As mentioned before, I'm unable to reproduce this with a stock install of the latest panel version. However, if you have more concrete reproduction steps that I can do to replicate this issue, I would be happy to fix this if it's genuinely an issue with the module.

**Closed as not planned** 2024-05-28 13:24 UTC
